apiVersion: v1
kind: Service
metadata:
  name: {{ include "agentmesh.fullname" . }}-trust-engine
  labels:
    {{- include "agentmesh.labels" . | nindent 4 }}
    app.kubernetes.io/component: trust-engine
spec:
  type: {{ .Values.trustEngine.service.type }}
  ports:
    - port: {{ .Values.trustEngine.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.trustEngine.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "agentmesh.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: trust-engine
